services:
  memphis-metadata:
    image: memphisos/memphis-metadata:docker-15.2.0-debian-11-r27
    networks:
      - memphis
    ports:
      - '5005:5005'
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005
networks:
  memphis:
    ipam:
      driver: default
