services:
  mongo:
    image: "memphisos/mongo:4.2"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "27017:27017"
  memphis-rest-gateway:
    image: "memphisos/memphis-rest-gateway:master"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "4444:4444"
    environment:
      - JWT_SECRET=JWT_TEST_PURPOSE
      - REFRESH_JWT_SECRET=REFRESH_JWT_TEST_PURPOSE
      - CONNECTION_TOKEN=memphis
      - ROOT_USER=root
      - MEMPHIS_HOST=memphis-cluster
      - HTTP_PORT=4444
networks:
  memphis:
    ipam:
      driver: default
