services:
  memphis-metadata:
    image: memphisos/memphis-metadata:15-docker
    networks:
      - memphis
    ports:
      - '5005:5005'
    environment:
      - POSTGRESQL_USERNAME=memphis
      - POSTGRESQL_PASSWORD=memphis
      - POSTGRESQL_DATABASE=memphis
      - POSTGRESQL_PORT_NUMBER=5005
  mongo:
    image: "memphisos/mongo:4.2"
    restart: on-failure
    pull_policy: always
    networks:
      - memphis
    ports:
      - "27017:27017"
networks:
  memphis:
    ipam:
      driver: default
